/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class XmlConfV4 extends ConfV4 {
  private transient long swigCPtr;

  protected XmlConfV4(long cPtr, boolean cMemoryOwn) {
    super(digidocJNI.XmlConfV4_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlConfV4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_XmlConfV4(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public XmlConfV4(String path, String schema) {
    this(digidocJNI.new_XmlConfV4__SWIG_0(path, schema), true);
  }

  public XmlConfV4(String path) {
    this(digidocJNI.new_XmlConfV4__SWIG_1(path), true);
  }

  public XmlConfV4() {
    this(digidocJNI.new_XmlConfV4__SWIG_2(), true);
  }

  public static XmlConfV4 instance() {
    long cPtr = digidocJNI.XmlConfV4_instance();
    return (cPtr == 0) ? null : new XmlConfV4(cPtr, false);
  }

  public int logLevel() {
    return digidocJNI.XmlConfV4_logLevel(swigCPtr, this);
  }

  public String logFile() {
    return digidocJNI.XmlConfV4_logFile(swigCPtr, this);
  }

  public String PKCS11Driver() {
    return digidocJNI.XmlConfV4_PKCS11Driver(swigCPtr, this);
  }

  public String proxyHost() {
    return digidocJNI.XmlConfV4_proxyHost(swigCPtr, this);
  }

  public String proxyPort() {
    return digidocJNI.XmlConfV4_proxyPort(swigCPtr, this);
  }

  public String proxyUser() {
    return digidocJNI.XmlConfV4_proxyUser(swigCPtr, this);
  }

  public String proxyPass() {
    return digidocJNI.XmlConfV4_proxyPass(swigCPtr, this);
  }

  public boolean proxyForceSSL() {
    return digidocJNI.XmlConfV4_proxyForceSSL(swigCPtr, this);
  }

  public boolean proxyTunnelSSL() {
    return digidocJNI.XmlConfV4_proxyTunnelSSL(swigCPtr, this);
  }

  public String digestUri() {
    return digidocJNI.XmlConfV4_digestUri(swigCPtr, this);
  }

  public String signatureDigestUri() {
    return digidocJNI.XmlConfV4_signatureDigestUri(swigCPtr, this);
  }

  public String ocsp(String issuer) {
    return digidocJNI.XmlConfV4_ocsp(swigCPtr, this, issuer);
  }

  public String TSUrl() {
    return digidocJNI.XmlConfV4_TSUrl(swigCPtr, this);
  }

  public String verifyServiceUri() {
    return digidocJNI.XmlConfV4_verifyServiceUri(swigCPtr, this);
  }

  public String PKCS12Cert() {
    return digidocJNI.XmlConfV4_PKCS12Cert(swigCPtr, this);
  }

  public String PKCS12Pass() {
    return digidocJNI.XmlConfV4_PKCS12Pass(swigCPtr, this);
  }

  public boolean PKCS12Disable() {
    return digidocJNI.XmlConfV4_PKCS12Disable(swigCPtr, this);
  }

  public boolean TSLAutoUpdate() {
    return digidocJNI.XmlConfV4_TSLAutoUpdate(swigCPtr, this);
  }

  public String TSLCache() {
    return digidocJNI.XmlConfV4_TSLCache(swigCPtr, this);
  }

  public boolean TSLOnlineDigest() {
    return digidocJNI.XmlConfV4_TSLOnlineDigest(swigCPtr, this);
  }

  public int TSLTimeOut() {
    return digidocJNI.XmlConfV4_TSLTimeOut(swigCPtr, this);
  }

  public void setProxyHost(String host) {
    digidocJNI.XmlConfV4_setProxyHost(swigCPtr, this, host);
  }

  public void setProxyPort(String port) {
    digidocJNI.XmlConfV4_setProxyPort(swigCPtr, this, port);
  }

  public void setProxyUser(String user) {
    digidocJNI.XmlConfV4_setProxyUser(swigCPtr, this, user);
  }

  public void setProxyPass(String pass) {
    digidocJNI.XmlConfV4_setProxyPass(swigCPtr, this, pass);
  }

  public void setProxyTunnelSSL(boolean enable) {
    digidocJNI.XmlConfV4_setProxyTunnelSSL(swigCPtr, this, enable);
  }

  public void setPKCS12Cert(String cert) {
    digidocJNI.XmlConfV4_setPKCS12Cert(swigCPtr, this, cert);
  }

  public void setPKCS12Pass(String pass) {
    digidocJNI.XmlConfV4_setPKCS12Pass(swigCPtr, this, pass);
  }

  public void setPKCS12Disable(boolean disable) {
    digidocJNI.XmlConfV4_setPKCS12Disable(swigCPtr, this, disable);
  }

  public void setTSLOnlineDigest(boolean enable) {
    digidocJNI.XmlConfV4_setTSLOnlineDigest(swigCPtr, this, enable);
  }

  public void setTSLTimeOut(int timeOut) {
    digidocJNI.XmlConfV4_setTSLTimeOut(swigCPtr, this, timeOut);
  }

  public void setTSUrl(String url) {
    digidocJNI.XmlConfV4_setTSUrl(swigCPtr, this, url);
  }

}
