/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ee.ria.libdigidocpp;

public class ConfV4 extends ConfV3 {
  private transient long swigCPtr;

  protected ConfV4(long cPtr, boolean cMemoryOwn) {
    super(digidocJNI.ConfV4_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfV4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        digidocJNI.delete_ConfV4(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ConfV4() {
    this(digidocJNI.new_ConfV4(), true);
  }

  public static ConfV4 instance() {
    long cPtr = digidocJNI.ConfV4_instance();
    return (cPtr == 0) ? null : new ConfV4(cPtr, false);
  }

}
